services:
  db:
    image: postgis/postgis
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - .env.db
    platform: linux/amd64
    user: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    volumes:
      - .:/code
    ports:
      - '8000:8000'
    env_file:
      - .env
      - .env.db
    depends_on:
      db:
        condition: service_healthy

volumes:
  db_data: